### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Lewsha02** [Archakov06/trycode#3]
Приложение упало.

**Comment by Archakov06** [comment]
Спасибо, ща чекну

**Comment by Lewsha02** [comment]
Хз, но у меня все еще не работает :(
Не могу продолжить проходить твой курс по твиттеру из-за этого

**Comment by Archakov06** [comment]
@Lewsha02 заработал. память закончилась почему-то

**Comment by Lewsha02** [comment]
Спасибо большое)
